version: '3'
services:
  db:
    image: postgres:11.4
    container_name: k8sdjango-postgres
    restart: always
    environment:
      POSTGRES_USER: k8sdjango_development
      POSTGRES_PASSWORD: b8n2maLRb7EUyv8c
      POSTGRES_DB: k8sdjango_development
    ports:
      - '5432:5432'
    volumes:
      - ./compose/postgres_data:/var/lib/postgresql/data
      - ./compose/postgres_data/postgresql.conf:/usr/local/etc/postgresql/11/postgresql.conf
      - ./compose/postgres_data/pg_hba.conf:/usr/local/etc/postgresql/11/pg_hba.conf

  redis:
    image: redis:5.0.5
    container_name: k8sdjango-redis
    restart: always
    ports:
     - '6379:6379'
    volumes:
      - ./compose/redis_data:/data
    depends_on:
      - "db"
