# redis
# dns: redis.k8sdjango.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: k8sdjango
spec:
  ports:
    - port: 9200
      targetPort: redis-port
  selector:
    app: redis-pod

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sdjango-redis
  namespace: k8sdjango
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: k8sdjango-redis
          image: redis:5.0.6
          imagePullPolicy: Always

          ports:
            - name: redis-port
              containerPort: 6379
